[package]
name = "transport_protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
async_async_io = "0.2"
byteorder = "1"
dre = { git = "https://github.com/Banyc/dre.git", tag = "v0.0.2" }
strict-num = "0.2"
tap = "1"
thiserror = "1"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
rand = "0.8"
